Works better on Ubuntu desktop, but still not well

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -220,39 +220,41 @@ printf "$dhcpd" > /etc/default/udhcpd
 	# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
 	# Old installation packages might not get network up. Try to restart it here.
 	# This is for updating edge below 0.5.0 to 0.5.0 or above. Remove this after couple of updates.
-pvs="/var/lib/spaceify/data/db/previous_edge_version"
-if [ -f $pvs ]; then pv=$(< $pvs); else pv="00000.00000.00000"; fi
-rm $pvs > /dev/null 2>&1
-ping -c 1 8.8.8.8 > /dev/null 2>&1
-if [ $? != 0 ] || [[ "$pv" < "00000.00005.00000" ]]; then
-
-	if [[ -n $(service network-manager status |& grep unrecognized) ]]; then
-
-		ifdown $eth > /dev/null 2>&1 || true
-		ifup $eth > /dev/null 2>&1 || true
-
-	elif [[ -n $(service network-manager status |& grep running) ]]; then
-
-		service network-manager restart > /dev/null 2>&1 || true
-
-		resolvconf -u
-
-	fi
-
-	. /var/lib/spaceify/data/scripts/wait_network.sh 0 300 50 "Please wait, restarting network."
-
-	if [ $? -ne 0 ]; then
-		printf "\e[41mThe installation is aborted because restarting the network failed. Run 'apt-get purge spaceify' to remove the incomplete installation. NOTICE: Save files that you want to preserve before removing the installation.\e[0m\n\n"
-		exit 1
-	else
-		printf "The network is restarted. Continuing the installation.\n"
-	fi
-
-fi
+#pvs="/var/lib/spaceify/data/db/previous_edge_version"
+#if [ -f $pvs ]; then pv=$(< $pvs); else pv="00000.00000.00000"; fi
+#rm $pvs > /dev/null 2>&1
+#ping -c 1 8.8.8.8 > /dev/null 2>&1
+#if [ $? != 0 ] || [[ "$pv" < "00000.00005.00000" ]]; then
+#
+#	if [[ -n $(service network-manager status |& grep unrecognized) ]]; then
+#
+#		ifdown $eth > /dev/null 2>&1 || true
+#		ifup $eth > /dev/null 2>&1 || true
+#
+#	elif [[ -n $(service network-manager status |& grep running) ]]; then
+#
+#		service network-manager restart > /dev/null 2>&1 || true
+#
+#		resolvconf -u
+#
+#	fi
+#
+#	. /var/lib/spaceify/data/scripts/wait_network.sh 0 300 50 "Please wait, restarting network."
+#
+#	if [ $? -ne 0 ]; then
+#		printf "\e[41mThe installation is aborted because restarting the network failed. Run 'apt-get purge spaceify' to remove the incomplete installation. NOTICE: Save files that you want to preserve before removing the installation.\e[0m\n\n"
+#		exit 1
+#	else
+#		printf "The network is restarted. Continuing the installation.\n"
+#	fi
+#
+#fi
 	# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
 
 	# ----- Update node.js to the latest stable release ----- #
+
 printf "\n\e[4mUpdating Node.js\e[0m\n\n"
+
 cd /var/lib/spaceify/code
 npm install npm -g
 npm cache clear -f
@@ -261,70 +263,9 @@ n 5.10.1
 npm uninstall bufferutil
 npm install -g bufferutil
 
-	# ----- Spaceify's DNS server must be on and other DNS mechanisms off ----- #
-		# - remove Spaceify's previous entries - #
-if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
-	sed -i -e "s/${comm_out_spaceify}//g" /etc/NetworkManager/NetworkManager.conf > /dev/null 2>&1 || true
-fi
 
-if [ -f /etc/dhcp/dhclient.conf ]; then
-	sed -i -e "s/${comm_out_spaceify}//g" -e "/${start_spaceify}/,/${end_spaceify}/d" /etc/dhcp/dhclient.conf > /dev/null 2>&1 || true
-fi
 
-sed -i -e "s/${comm_out_spaceify}//g" -e "/${start_spaceify}/,/${end_spaceify}/d" /etc/resolvconf/resolv.conf.d/base > /dev/null 2>&1 || true
-
-		# - disable dnsmasq - #
-if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
-	netm=$( sed -i -e "/dns/ s/^/${comm_out_spaceify}/" /etc/NetworkManager/NetworkManager.conf )
-fi
-
-		# - keep localhost - #
-if [ -f /etc/dhcp/dhclient.conf ]; then
-	hdh=$(grep "prepend domain-name-servers" /etc/dhcp/dhclient.conf)
-
-	if [ -n "$hdh" ]; then
-		dhcl=$( sed -e "/prepend domain-name-servers/ s/^/${comm_out_spaceify}/" /etc/dhcp/dhclient.conf )
-		dhcl=$( echo "$dhcl" | sed "/prepend domain-name-servers/a ${start_spaceify}\nprepend domain-name-servers 127.0.0.1;\n${end_spaceify}" )
-	else
-		dhcl=$(< /etc/dhcp/dhclient.conf)
-		dhcl="${dhcl}\n${start_spaceify}\nprepend domain-name-servers 127.0.0.1;\n${end_spaceify}"
-	fi
-
-	printf "$dhcl" > /etc/dhcp/dhclient.conf
-fi
-
-		# - direct to localhost - #
-base=$( sed -e "s/^/${comm_out_spaceify}/" /etc/resolvconf/resolv.conf.d/base )
-base="${base}\n${start_spaceify}\nnameserver 127.0.0.1\n${end_spaceify}"
-printf "$base" > /etc/resolvconf/resolv.conf.d/base
-
-		# - try to apply the changes - #
-if [[ -n $(service network-manager status |& grep unrecognized) ]]; then
-
-	ifdown $eth > /dev/null 2>&1 || true
-	ifup $eth > /dev/null 2>&1 || true
-
-elif [[ -n $(service network-manager status |& grep running) ]]; then
-
-	service network-manager restart > /dev/null 2>&1 || true
-
-	resolvconf -u
-
-fi
-
-. /var/lib/spaceify/data/scripts/wait_network.sh 0 300 50 "Please wait, restarting network."
-
-if [ $? -ne 0 ]; then
-	printf "\e[41mThe installation is aborted because restarting the network failed. Run 'apt-get purge spaceify' to remove the incomplete installation. NOTICE: Save files that you want to preserve before removing the installation.\e[0m\n\n"
-	exit 1
-else
-	printf "The network is restarted. Continuing the installation.\n"
-fi
-
-		# - Start Spaceify's DNS server - #
-service spaceifydns restart > /dev/null 2>&1 || true
-
-	# ----- Add custom iptables chains for Spaceify - To avoid duplicates, delete existing chains first ----- #
+# ----- Add custom iptables chains for Spaceify - To avoid duplicates, delete existing chains first ----- #
 
 		# - -- Delete mangle chain -- - #
 #/sbin/iptables -t mangle -D PREROUTING -j Spaceify-mangle > /dev/null 2>&1 || true
@@ -623,20 +564,20 @@ printf "\n\e[4mRestarting edge nodes network and Spaceify's services\e[0m\n"
 
 #service udhcpd restart
 
-printf "\nTrying to restart network. If the network does not restart, please do it manually or reboot the computer.\n"
-if [[ -n $(service network-manager status |& grep unrecognized) ]]; then
+#printf "\nTrying to restart network. If the network does not restart, please do it manually or reboot the computer.\n"
+#if [[ -n $(service network-manager status |& grep unrecognized) ]]; then
 
-	ifdown $eth > /dev/null 2>&1 || true
-	ifup $eth > /dev/null 2>&1 || true
+#	ifdown $eth > /dev/null 2>&1 || true
+#	ifup $eth > /dev/null 2>&1 || true
 
-else
-	service network-manager restart > /dev/null 2>&1 || true
+#else
+	#service network-manager restart > /dev/null 2>&1 || true
 
-	resolvconf -u
+	#resolvconf -u
 
 	ifconfig ${wlan} down
 	ifconfig ${wlan} 10.0.0.1 netmask 255.255.255.0 up
-fi
+#fi
 
 if [[ "$is_internal" -eq "1" ]]; then
 	service hostapd restart > /dev/null 2>&1 || true
@@ -649,14 +590,93 @@ fi
 #/sbin/iptables -t nat -X DOCKER > /dev/null 2>&1 || true
 #service docker restart > /dev/null 2>&1 || true
 
-printf "\nRestarting the services.\n"
-service spaceifydns restart > /dev/null 2>&1 || true
-service spaceifyipt restart > /dev/null 2>&1 || true
-service spaceify restart > /dev/null 2>&1 || true
-service spaceifyappman restart > /dev/null 2>&1 || true
-service spaceifyhttp restart > /dev/null 2>&1 || true
+
+
+
+#printf "\nRestarting the services.\n"
+#service spaceifydns restart > /dev/null 2>&1 || true
+#service spaceifyipt restart > /dev/null 2>&1 || true
+#service spaceify restart > /dev/null 2>&1 || true
+#service spaceifyappman restart > /dev/null 2>&1 || true
+#service spaceifyhttp restart > /dev/null 2>&1 || true
 
 #service monit restart > /dev/null 2>&1 || true
+
+
+
+
+################## DNS CONFIGURATION #########################################
+
+# ----- Spaceify's DNS server must be on and other DNS mechanisms off ----- #
+		# - remove Spaceify's previous entries - #
+if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
+	sed -i -e "s/${comm_out_spaceify}//g" /etc/NetworkManager/NetworkManager.conf > /dev/null 2>&1 || true
+fi
+
+if [ -f /etc/dhcp/dhclient.conf ]; then
+	sed -i -e "s/${comm_out_spaceify}//g" -e "/${start_spaceify}/,/${end_spaceify}/d" /etc/dhcp/dhclient.conf > /dev/null 2>&1 || true
+fi
+
+sed -i -e "s/${comm_out_spaceify}//g" -e "/${start_spaceify}/,/${end_spaceify}/d" /etc/resolvconf/resolv.conf.d/base > /dev/null 2>&1 || true
+
+		# - disable dnsmasq - #
+if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
+	netm=$( sed -i -e "/dns/ s/^/${comm_out_spaceify}/" /etc/NetworkManager/NetworkManager.conf )
+fi
+
+		# - keep localhost - #
+if [ -f /etc/dhcp/dhclient.conf ]; then
+	hdh=$(grep "prepend domain-name-servers" /etc/dhcp/dhclient.conf)
+
+	if [ -n "$hdh" ]; then
+		dhcl=$( sed -e "/prepend domain-name-servers/ s/^/${comm_out_spaceify}/" /etc/dhcp/dhclient.conf )
+		dhcl=$( echo "$dhcl" | sed "/prepend domain-name-servers/a ${start_spaceify}\nprepend domain-name-servers 127.0.0.1;\n${end_spaceify}" )
+	else
+		dhcl=$(< /etc/dhcp/dhclient.conf)
+		dhcl="${dhcl}\n${start_spaceify}\nprepend domain-name-servers 127.0.0.1;\n${end_spaceify}"
+	fi
+
+	printf "$dhcl" > /etc/dhcp/dhclient.conf
+fi
+
+		# - direct to localhost - #
+base=$( sed -e "s/^/${comm_out_spaceify}/" /etc/resolvconf/resolv.conf.d/base )
+base="${base}\n${start_spaceify}\nnameserver 127.0.0.1\n${end_spaceify}"
+printf "$base" > /etc/resolvconf/resolv.conf.d/base
+
+		# - try to apply the changes - #
+#if [[ -n $(service network-manager status |& grep unrecognized) ]]; then
+
+#	ifdown $eth > /dev/null 2>&1 || true
+#	ifup $eth > /dev/null 2>&1 || true
+
+#elif [[ -n $(service network-manager status |& grep running) ]]; then
+
+	#service network-manager restart > /dev/null 2>&1 || true
+
+	#resolvconf -u
+	pkill dnsmasq	
+#fi
+
+#The debhelper-generated stuff should appaear in place of the following comment
+
+#DEBHELPER#
+
+/var/lib/spaceify/data/scripts/wait_network.sh 0 300 50 "Please wait, restarting network."
+
+if [ $? -ne 0 ]; then
+	printf "\e[41mThe installation is aborted because restarting the network failed. Run 'apt-get purge spaceify' to remove the incomplete installation. NOTICE: Save files that you want to preserve before removing the installation.\e[0m\n\n"
+	exit 1
+else
+	printf "The network is restarted. Continuing the installation.\n"
+fi
+
+# - Start Spaceify's DNS server - #
+#service spaceifydns restart > /dev/null 2>&1 || true
+
+################## DNS CONFIGURATION ENDS #########################################
+
+
 
 # ----------
 # ----------
@@ -678,6 +698,4 @@ printf "\n\e[42mSpaceify version $vs is now installed\e[0m\n\n"
 # Script is found here after installation, if testing is required (eg. finding where the script fails): /var/lib/dpkg/info/spaceify.postinst
 # After changing the script run dpkg-reconfigure spaceify
 
-#The debhelper-generated stuff should appaear in place of the following coment
 
-#DEBHELPER#
